version: '3.3'

services:
    data:
        ports:
            - '9000:9000'
            - '9090:9090'
        container_name: minio
        volumes:
            - '~/minio/data:/data'
        environment:
            - MINIO_ROOT_USER=ROOTNAME
            - MINIO_ROOT_PASSWORD=CHANGEME123
        image: /data
