version: '3.1'

services:
    verdaccio:
        image: verdaccio/verdaccio
        container_name: 'verdaccio'
        networks:
            - node-network
        environment:
            - VERDACCIO_PORT=4873
            - VERDACCIO_PROTOCOL=https
            - VERDACCIO_USER_UID=0
            - VERDACCIO_USER_NAME=root
        ports:
            - '4873:4873'
        volumes:
            - './storage:/verdaccio/storage'
            - './conf:/verdaccio/conf'
            - './plugins:/verdaccio/plugins'
networks:
    node-network:
        driver: bridge
